version: "3.9"
services:
  db:
    image: postgres:15.0-alpine
    container_name: $DB_HOST
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - ./.env
    command: >
      sh -c "
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        python3 manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - ./menu_tags:/app/menu_tags
      - static_volume:/static
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
