# Generated by Django 5.0.2 on 2024-02-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название пункта меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Этот параметр используется для указания адреса, на который следует перейти из текущего пункта меню. Если не указан, то ищем потомков данного пункта меню и автоматически создаем подменю на основе их данных.', max_length=50, verbose_name='URL-адрес'),
        ),
    ]
